scope\(success\) is unreachable, at position SourceLocation\(filename = (.*)/ScopeSuccessBlockEarlierScopeSuccess\.loci, range = \(line 6, column 3\) to \(line 8, column 4\)\), due to later always throwing scope\(success\), at position SourceLocation\(filename = (.*)/ScopeSuccessBlockEarlierScopeSuccess\.loci, range = \(line 9, column 3\) to \(line 11, column 4\)\)\.
